name: flutter_amplify_auth_ui
description: Flutter plugin that automatically generates Auth components based on an Amplify CLI configuration.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.3 <3.0.0'

dependencies:
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
